---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: semaphore
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: semaphore
  dependsOn:
    - name: external-secrets-stores
    - name: cnpg-cluster
  interval: 1h
  path: "./kubernetes/apps/selfhosted/semaphore/app"
  postBuild:
    substitute:
      APP: semaphore
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
