---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: keycloak
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
    - name: rook-ceph-cluster
    - name: external-secrets-stores
  interval: 1h
  path: "./kubernetes/apps/security/keycloak/app"
  postBuild:
    substitute:
      APP: keycloak
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CLAIM: keycloak
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: security
  timeout: 5m
  wait: false
