---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: "${VOLSYNC_CLAIM:=${APP}}"
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - "${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_STORAGECLASS:=ceph-block}"
    copyMethod: Snapshot
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
    moverSecurityContext:
      runAsUser: ${APP_UID:=1000}
      runAsGroup: ${APP_GID:=1000}
      fsGroup: ${APP_GID:=1000}
    repository: "${APP}-volsync-secret"
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
