---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volsync-kopia-repository-${APP}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: ${VOLSYNC_NAMESPACE:=selfhosted}
    name: volsync-kopia-repository
  nfs:
    server: 192.168.1.100
    path: /mnt/zfs/pvc/VolsyncKopia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-kopia-repository
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: volsync-kopia-repository-${APP}
  resources:
    requests:
      storage: 100Gi
