---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: keycloak-secret
    creationPolicy: Owner
    template:
      data:
        # Keycloak admin credentials
        KEYCLOAK_ADMIN: "{{ .keycloak_admin_user }}"
        KEYCLOAK_ADMIN_PASSWORD: "{{ .keycloak_admin_password }}"
        # Database credentials
        KC_DB_PASSWORD: "{{ .keycloak_db_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: keycloak
        INIT_POSTGRES_HOST: homelab-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_PASS: "{{ .keycloak_db_password }}"
        INIT_POSTGRES_USER: keycloak
  dataFrom:
    - extract:
        key: keycloak
      rewrite:
        - regexp:
            source: "(.*)"
            target: "keycloak_$1"
    - extract:
        key: cloudnative-pg
