---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: volsync
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./kubernetes/apps/selfhosted/paperless/app"
  postBuild:
    substitute:
      APP: paperless
      APP_UID: "1000"
      APP_GID: "100"
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
