---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  interval: 1h
  path: "./kubernetes/apps/selfhosted/paperless/app"
  postBuild:
    substitute:
      APP: paperless
      APP_UID: "1000"
      APP_GID: "65542"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
