---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: semaphore
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: semaphore-secret
    creationPolicy: Owner
    template:
      data:
        # Semaphore admin
        SEMAPHORE_ADMIN: "{{ .semaphore_admin_user }}"
        SEMAPHORE_ADMIN_NAME: "{{ .semaphore_admin_name }}"
        SEMAPHORE_ADMIN_PASSWORD: "{{ .semaphore_admin_password }}"
        SEMAPHORE_ADMIN_EMAIL: "{{ .semaphore_admin_email }}"
        # Semaphore encryption keys
        SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ .semaphore_access_key_encryption }}"
        SEMAPHORE_COOKIE_HASH: "{{ .semaphore_cookie_hash }}"
        SEMAPHORE_COOKIE_ENCRYPTION: "{{ .semaphore_cookie_encryption }}"
        # OIDC
        OIDC_CLIENT_ID: "{{ .semaphore_oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .semaphore_oidc_client_secret }}"
        # Database credentials
        SEMAPHORE_DB_USER: "{{ .semaphore_db_user }}"
        SEMAPHORE_DB_PASS: "{{ .semaphore_db_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: semaphore
        INIT_POSTGRES_HOST: homelab-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_PASS: "{{ .semaphore_db_password }}"
        INIT_POSTGRES_USER: "{{ .semaphore_db_user }}"
  dataFrom:
    - extract:
        key: semaphore
      rewrite:
        - regexp:
            source: "(.*)"
            target: "semaphore_$1"
    - extract:
        key: cloudnative-pg
