---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-operator-ui
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - "flux.${CLUSTER_DOMAIN}"
  rules:
    - backendRefs:
        - name: flux-operator
          port: 9080
